// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package financetracker

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, password) VALUES (?1, ?2)
`

type CreateUserParams struct {
	Email    string
	Password string
}

// Creates a new user by email
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Email, arg.Password)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password, created_at FROM users WHERE email = ?1 LIMIT 1
`

// Retrieves a single user by the email
func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
